---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: /src/
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: /src/
    schedule:
      interval: daily
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directories:
      - /modules/lambda/
    schedule:
      interval: daily
    open-pull-requests-limit: 10
